legendary-launch-offline = Játékok indítása offline módban, ha lehetséges
legendary-enable-offline-mode = Offline mód engedélyezése
legendary-offline-mode = Offline mód
legendary-all-activated-ubisoft = Az összes játék már aktiválva lett a(z) { $companyAccount } fiókodon.
legendary-continue-activation = Biztosan aktiválni szeretnéd a játékokat a(z) { $companyAccount } fiókodon?
legendary-games-activate-success = Az összes játék sikeresen aktiválva lett a(z) { $companyAccount } fiókodon.
legendary-activate-games = Játékok aktiválása
legendary-games-activate-failure = Nem sikerült aktiválni a játékokat a(z) { $companyAccount } fiókodon. Indok: { $reason }.
legendary-activate-next-confirm = Szeretnéd aktiválni a következő játékot?
legendary-star-wars-message = Az Erő legyen veled, padavan.
legendary-import-third-party-launcher-games = A játékok importálásához szükséges a(z) { $thirdPartyLauncherName }
legendary-authenticate-alternative-label = Hitelesítés alternatív módszerrel
legendary-alternative-auth-instructions-first = 1. Jelentkezz be az Epic Games Store-ba a böngésződben.
legendary-alternative-auth-instructions-second = 2. Nyissa meg a hitelesítési kód URL-jét, amely az alábbi beviteli mezőben látható.
legendary-alternative-auth-instructions-third = 3. Illessze be az "authorizationCode” értékét az alábbi beviteli mezőbe, majd kattintson az "authenticate” gombra.
legendary-disable = Letiltás
legendary-enable = Engedélyezés
legendary-game-import-failure = Játékok importálása sikertelen. Indok: { $reason }.
legendary-language-code = Nyelv (RFC 1766 formátumú kód)
legendary-launcher-update-source = Legendary frissítési forrása
