common-launcher-custom-path = Launcher Path
common-games-installation-path = Games Installation Path
common-download-size = Download Size:
common-install-size = Install Size:
common-uninstall-game-confirm = Are you sure you want to uninstall { $gameTitle }?
common-download-settings = Downloads
common-display-download-task-finished-notifications = Display desktop notifications about finished tasks
common-display-download-speed-in-bits = Display download speed in bits per second
common-download-all-dlcs = Download all DLCs
common-unattended-install = Enable unattended installation mode
common-unattended-install-tool-tip = You won't have to choose anything in the installer window and the installation will start automatically after downloading the required information.
common-max-workers = Maximum number of worker processes
common-max-shared-memory = Maximum amount of shared memory (MB)
common-connection-timeout = Connection timeout (sec)
common-after-download-complete = Action after download is complete
common-auto-remove-completed-downloads = Automatically remove completed downloads from list
common-system-shutdown-countdown = System will be turned off soon...
common-system-restart-countdown = System will be restarted soon...
common-system-hibernate-countdown = System will be hibernated soon...
common-system-suspend-countdown = System will be suspended soon...
common-disable = Disable
common-enable = Enable
common-space-available = Space Available:
common-after-installing = After Installing:
common-downloaded = Downloaded
common-eta = ETA:
common-download-speed = Download Speed:
common-disk-speed = Disk Usage:
common-elapsed = Elapsed:
common-verifying = Verifying...
common-verifying-large-file = Verifying large file "{ $fileName }": { $progress }
common-downloading-update = Downloading update...
common-finishing-installation = Finishing installation...
common-finishing-update = Finishing update...
common-finishing-repair = Finishing repair...
common-pause-download = Pause
common-resume-download = Resume
common-download-paused = Paused
common-installation-finished = Installation finished. Have fun.
common-update-finished = Update finished. Have fun.
common-repair-finished = Repair finished. Have fun.
common-sync-game-saves = Sync game saves to the cloud
common-syncing = Syncing { $gameTitle } game saves to the cloud...
common-sync-error = An error occurred while syncing { $gameTitle } game saves to the cloud.
common-import-installed-game = Import installed game
common-importing-game = Importing { $gameTitle }...
common-import-finished = Import finished. Have fun.
common-game-import-failure = Failed to import game. Reason: { $reason }.
common-download-manager = Download Manager
common-download-status = Status
common-progress = Progress
common-download-completed-column = Completed
common-download-queued = Queued
common-download-running = Running
common-download-canceled = Canceled
common-download-completed = Completed
common-current-download-summary = Summary of the current download
common-remove-entry = Remove entry
common-remove-entry-confirm = Are you sure you want to remove { $entryName } from list?
common-move-entry-top = Move entry to top
common-move-entry-up = Move entry up
common-move-entry-down = Move entry down
common-move-entry-bottom = Move entry to bottom
common-remove-completed-downloads = Remove completed downloads
common-remove-completed-downloads-confirm = Are you sure you want to remove all completed downloads from list?
common-remove-selected-entries-confirm = Are you sure you want to remove selected entries from list?
common-select-all-entries = Select all entries
common-repair = Repair
common-advanced-options = Advanced Options
common-extra-content = Extra Content
common-cache = Cache
common-clear-cache = Clear cache
common-auto-clear-cache = Automatically clear cache
common-once-a-month = Once a month
common-once-every3-months = Once every 3 months
common-once-every6-months = Once every 6 months
common-clear-cache-confirm = Are you sure you want to clear cache?
common-check-log = Check the log files for more information.
common-sync-game-saves-warn = Cloud saves feature is experimental. It's recommended to backup game saves in case something goes wrong.
common-edit-selected-download-properties = Edit entry properties
common-open-download-directory = Open download directory
common-path-not-exists-error = The specified path does not exist.
common-task = Task
common-download-properties = Download Properties
common-migration-completed = Migration completed successfully.
common-migration-no-games = No games found for migration.
common-sign-out = Sign out
common-troubleshooting-information = Troubleshooting information
common-playnite-version = Playnite version
common-plugin-version = Plugin version
common-launcher-version = Launcher version
common-launcher-binary = Launcher binary
common-copy-raw-data-to-clipboard = Copy raw data to clipboard
common-log-files-path = Log Files Path
common-report-bug = Report a bug
common-new-version-available = A new version is available: { $appName } { $appVersion }.
common-no-updates-available = No updates available.
common-view-changelog = View changelog
common-disable-game-update-checking = Disable update checking
common-startup-arguments = Startup arguments
common-language-code = Language (code in RFC 1766 format)
common-launcher-settings = Modify launch settings
common-alternative-exe = Alternative executable file
common-cloud-saves = Cloud saves
common-check-all-dlcs = Check all DLCs
common-check-all-content = Check all
common-save-path = Save path
common-cloud = Cloud
common-auto-sync-saves = Sync saves to the cloud
common-calculate-path = Calculate path
common-cloud-saves-not-supported = This game doesn't support cloud saves.
common-manual-sync-saves = Manual sync saves
common-sync = Sync
common-download = Download
common-upload = Upload
common-force-action = Force action
common-cloud-save-confirm = Cloud saves feature is experimental. It's recommended to backup game saves in case something goes wrong. Are you sure you want to continue?
common-sync-playtime = Sync playtime to the cloud
common-uploading-playtime = Uploading { $gameTitle } game playtime to the cloud...
common-upload-playtime-error = An error occurred while uploading { $gameTitle } game playtime to the cloud.
common-move = Move
common-move-confirm = Are you sure you want to move { $appName } to "{ $path }"? This may take a long time.
common-moving-game = Moving { $appName } to "{ $path }"...
common-move-game-success = { $appName } has been successfully moved to "{ $path }".
common-move-game-error = An error occurred while moving { $appName } to "{ $path }".
common-installed-dlcs = Installed DLCs
common-available-dlcs = Available DLCs
common-manage-dlcs = Manage DLCs
common-uninstall-selected-dlcs = Are you sure you want to uninstall selected DLCs?
common-no-installed-dlcs = No installed DLCs.
common-no-available-dlcs = No available DLCs.
common-auto-update = Automatically update games
common-games-update-policy = Check for games updates
common-check-updates-every-playnite-startup = On every Playnite startup
common-remove-game-launch-settings = Remove launch settings
common-additional-services = Additional services
common-signed-in-as = Signed in as { $userName }
common-sign-out-confirm = Are you sure you want to sign out?
common-permission-error = User doesn't have write access to the specified path. Change permissions or launch Playnite as administrator.
common-check-for-games-updates-button = Check for games updates
common-not-enough-space = Not enough free disk space.
common-checking-for-updates = Checking for updates...
common-uninstall-success =
    { $count ->
        [one] { $appName } has been successfully uninstalled.
       *[other] Following games have been successfully uninstalled: { $appName }.
    }
common-uninstall-error =
    { $count ->
       *[other] Cannot uninstall following games: { $appName }.
    }
common-games = Games
common-launcher-update-policy = Check for launcher updates
common-launcher-not-installed = { $launcherName } is not installed.
common-panel = { $pluginShortName } Panel
common-download-manager-whats-up = The download will start soon. You can see its status by accessing { $pluginShortName } Panel via Menu => View or sidebar.
common-download-already-exists =
    { $count ->
        [one] { $appName } is already in the download list. You can see status of the download by accessing { $pluginShortName } Panel via Menu => View or sidebar.
       *[other] Following games are already in the download list: { $appName }. You can see status of the download by accessing { $pluginShortName } Panel via Menu => View or sidebar.
    }
common-migrate-games-epic = Migrate all games from { $originalPluginShortName } plugin
common-migrating-games-epic = Migrating all games from { $originalPluginShortName } plugin...
common-migration-confirm = All games will be removed from { $originalPluginShortName } plugin and moved to { $pluginShortName }. Are you sure you want to do this?
common-games-updates-underway = Updates for games from { $updatesSourceName } are being downloaded.
common-instance-notice = Only one instance of { $pluginShortName } may install/import/move applications at a time. Do you want to pause download manager tasks to continue?
