common-launcher-custom-path = Percorso del launcher
common-games-installation-path = Percorso giochi
common-download-size = Dimensioni download:
common-install-size = Dimensione installazione:
common-uninstall-game-confirm = Confermi di voler disinstallare { $gameTitle }?
common-download-settings = Download
common-display-download-task-finished-notifications = Visualizza le notifiche sul desktop per le attività terminate
common-display-download-speed-in-bits = Visualizza la velocità di download in bit al secondo
common-unattended-install = Abilita la modalità d'installazione automatica
common-unattended-install-tool-tip = Non sarà necessario scegliere nulla nella finestra d'installazione e l'installazione inizierà automaticamente dopo aver scaricato le informazioni richieste.
common-max-workers = Numero massimo di processi di lavoro
common-max-shared-memory = Quantità massima di memoria condivisa (MB)
common-connection-timeout = Timeout connessione (sec)
common-after-download-complete = Dopo il completamento del download
common-auto-remove-completed-downloads = Rimuovi automaticamente i download completati dalla lista
common-system-shutdown-countdown = Il sistema verrà spento a breve...
common-system-restart-countdown = Il sistema verrà riavviato a breve...
common-system-hibernate-countdown = Il sistema verrà ibernato presto...
common-system-suspend-countdown = Il sistema verrà sospeso a breve...
common-space-available = Spazio disponibile:
common-after-installing = Dopo l'installazione:
common-downloaded = Scaricato
common-eta = Tempo rimanente:
common-download-speed = Velocità di download:
common-disk-speed = Utilizzo del disco:
common-elapsed = Trascorso:
common-verifying = Verifica...
common-verifying-large-file = Verifica file di grandi dimensioni "{ $fileName }": { $progress }
common-downloading-update = Download aggiornamento...
common-finishing-installation = Installazione quasi finita...
common-finishing-update = Aggiornamento quasi finito...
common-finishing-repair = Ripristino quasi finito...
common-pause-download = Pausa
common-resume-download = Riprendi
common-download-paused = In pausa
common-installation-finished = Installazione finita. Buon divertimento.
common-update-finished = Aggiornamento finito. Divertiti.
common-repair-finished = Riparazione finita. Divertiti.
common-sync-error = Si è verificato un errore nella sincronizzazione dei salvataggi di { $gameTitle } nel cloud.
common-import-installed-game = Importa gioco installato
common-importing-game = Importazione { $gameTitle }...
common-import-finished = Importazione finita. Buon divertimento.
common-download-manager = Gestore download
common-download-status = Stato
common-progress = Progresso
common-download-completed-column = Completato
common-download-queued = In coda
common-download-running = In esecuzione
common-download-canceled = Annullato
common-download-completed = Completato
common-current-download-summary = Riepilogo del download attuale
common-remove-entry = Rimuovi voce
common-remove-entry-confirm = Sei sicuro di voler rimuovere { $entryName } dalla lista?
common-move-entry-top = Sposta all'inizio
common-move-entry-up = Sposta su
common-move-entry-down = Sposta giù
common-move-entry-bottom = Sposta in fondo
common-remove-completed-downloads = Rimuovi i download completati
common-remove-completed-downloads-confirm = Sei sicuro di voler rimuovere tutti i download completati dalla lista?
common-remove-selected-entries-confirm = Sei sicuro di voler rimuovere le voci selezionate dalla lista?
common-select-all-entries = Seleziona tutto
common-repair = Ripara
common-advanced-options = Opzioni avanzate
common-cache = Cache
common-clear-cache = Svuota cache
common-auto-clear-cache = Cancella cache automaticamente
common-once-a-month = Una volta al mese
common-once-every3-months = Una volta ogni 3 mesi
common-once-every6-months = Una volta ogni 6 mesi
common-clear-cache-confirm = Sei sicuro di voler cancellare la cache?
common-check-log = Controllare i log per ulteriori informazioni.
common-edit-selected-download-properties = Modifica proprietà
common-open-download-directory = Apri cartella download
common-path-not-exists-error = Il percorso specificato non esiste.
common-task = Attività
common-download-properties = Proprietà di download
common-migration-completed = Migrazione completata con successo.
common-migration-no-games = Nessun gioco trovato per la migrazione.
common-sign-out = Disconnettiti
common-troubleshooting-information = Informazioni e risoluzione dei problemi
common-playnite-version = Versione di Playnite
common-plugin-version = Versione plugin
common-launcher-version = Versione launcher
common-launcher-binary = Eseguibile launcher
common-copy-raw-data-to-clipboard = Copia dati grezzi negli appunti
common-log-files-path = Percorso file di log
common-report-bug = Segnala un bug
common-new-version-available = È disponibile una nuova versione: { $appName } { $appVersion }.
common-no-updates-available = Nessun aggiornamento disponibile.
common-view-changelog = Visualizza changelog
common-disable-game-update-checking = Disattiva controllo aggiornamenti
common-startup-arguments = Argomenti di avvio
common-launcher-settings = Modifica impostazioni di avvio
common-alternative-exe = File eseguibile alternativo
common-check-all-content = Seleziona tutto
common-move = Sposta
common-move-confirm = Sei sicuro di voler spostare { $appName } in "{ $path }"? Potrebbe richiedere molto tempo.
common-moving-game = Spostamento { $appName } in "{ $path }"...
common-move-game-success = { $appName } è stato spostato con successo in "{ $path }".
common-move-game-error = Si è verificato un errore durante lo spostamento di { $appName } in "{ $path }".
common-auto-update = Aggiorna giochi automaticamente
common-games-update-policy = Controlla aggiornamenti giochi
common-check-updates-every-playnite-startup = Ad ogni avvio di Playnite
common-remove-game-launch-settings = Rimuovi impostazioni di avvio
common-signed-in-as = Accesso effettuato come { $userName }
common-sign-out-confirm = Sei sicuro di volerti disconnettere?
common-permission-error = L'utente non ha accesso in scrittura al percorso specificato. Cambia i permessi o avvia Playnite come amministratore.
common-check-for-games-updates-button = Controlla aggiornamenti giochi
common-not-enough-space = Non c'è abbastanza spazio libero su disco.
common-checking-for-updates = Controllo aggiornamenti...
common-uninstall-success =
    { $count ->
        [one] { $appName } è stato disinstallato con successo.
       *[other] I seguenti giochi sono stati disinstallati con successo: { $appName }.
    }
common-uninstall-error =
    { $count ->
       *[other] Impossibile disinstallare i seguenti giochi: { $appName }.
    }
common-games = Giochi
common-launcher-update-policy = Controlla aggiornamenti del launcher
common-launcher-not-installed = { $launcherName } non è installato.
common-panel = Pannello { $pluginShortName }
common-download-manager-whats-up = Il download inizierà a breve. Puoi vederne lo stato accedendo al pannello { $pluginShortName } tramite Menu => Visualizza o dalla barra laterale.
common-download-already-exists =
    { $count ->
        [one] { $appName } è già nella lista dei download. È possibile visualizzare lo stato del download accedendo al pannello { $pluginShortName } tramite Menu => Visualizza o dalla barra laterale.
       *[other] I seguenti giochi sono già nella lista dei download: { $appName }. Puoi vedere lo stato del download accedendo al pannello { $pluginShortName } tramite Menu => Visualizza o dalla barra laterale.
    }
common-migrate-games-original = Migra tutti i giochi dal plugin { $originalPluginShortName }
common-migrating-games-original = Migrazione di tutti i giochi dal plugin { $originalPluginShortName }...
common-migration-confirm = Tutti i giochi saranno rimossi dal plugin { $originalPluginShortName } e spostati in { $pluginShortName }. Sei sicuro di volerlo fare?
common-games-updates-underway = Gli aggiornamenti dei giochi di { $updatesSourceName } sono in download.
common-instance-notice = Solo un'istanza di { $pluginShortName } può installare/importare/spostare applicazioni alla volta. Si desidera mettere in pausa le attività del gestore download per continuare?
