common-launcher-custom-path = Ścieżka launchera
common-games-installation-path = Ścieżka instalacji gier
common-download-size = Rozmiar pobierania:
common-install-size = Rozmiar instalacji:
common-uninstall-game-confirm = Czy na pewno chcesz odinstalować program { $gameTitle }?
common-download-settings = Pobieranie
common-display-download-task-finished-notifications = Wyświetlaj powiadomienia na pulpicie o zakończonych zadaniach
common-display-download-speed-in-bits = Wyświetlaj prędkość pobierania w bitach na sekundę
common-download-all-dlcs = Pobieraj wszystkie DLC
common-unattended-install = Włącz tryb instalacji nienadzorowanej
common-unattended-install-tool-tip = Nie będziesz niczego musiał wybierać w oknie instalatora, a instalacja rozpocznie się automatycznie po pobraniu wymaganych informacji.
common-max-workers = Maksymalna liczba procesów roboczych
common-max-shared-memory = Maksymalna ilość pamięci współdzielonej (MB)
common-connection-timeout = Limit czasu połączenia (sek)
common-after-download-complete = Akcja po zakończeniu pobierania
common-auto-remove-completed-downloads = Automatycznie usuwaj ukończone pobrania z listy
common-system-shutdown-countdown = System niedługo zostanie wyłączony...
common-system-restart-countdown = System niedługo zostanie zrestartowany...
common-system-hibernate-countdown = System niedługo zostanie przełączony w stan hibernacji...
common-system-suspend-countdown = System niedługo zostanie zawieszony...
common-disable = Wyłącz
common-enable = Włącz
common-space-available = Dostępne miejsce:
common-after-installing = Po zainstalowaniu:
common-downloaded = Pobrano
common-eta = Pozostało:
common-download-speed = Prędkość pobierania:
common-disk-speed = Użycie dysku:
common-elapsed = Upłynęło:
common-verifying = Weryfikowanie...
common-verifying-large-file = Weryfikowanie dużego pliku "{ $fileName }": { $progress }
common-downloading-update = Pobieranie aktualizacji...
common-finishing-installation = Kończenie instalacji...
common-finishing-update = Kończenie aktualizacji...
common-finishing-repair = Kończenie naprawy...
common-pause-download = Wstrzymaj
common-resume-download = Wznów
common-download-paused = Wstrzymane
common-installation-finished = Instalacja została zakończona. Dobrej zabawy.
common-update-finished = Aktualizacja zakończona. Dobrej zabawy.
common-repair-finished = Naprawa zakończona. Dobrej zabawy.
common-sync-game-saves = Synchronizuj zapisy gier z chmurą
common-syncing = Synchronizowanie zapisów gry { $gameTitle } z chmurą...
common-sync-error = Wystąpił błąd podczas synchronizacji zapisów gry { $gameTitle } z chmurą.
common-import-installed-game = Importuj zainstalowaną grę
common-importing-game = Importowanie gry { $gameTitle }...
common-import-finished = Importowanie zakończone. Dobrej zabawy.
common-game-import-failure = Nie udało się zaimportować gry. Powód: { $reason }.
common-download-manager = Menedżer pobierania
common-download-status = Stan
common-progress = Postęp
common-download-completed-column = Ukończono
common-download-queued = W kolejce
common-download-running = Uruchomione
common-download-canceled = Anulowane
common-download-completed = Ukończone
common-current-download-summary = Podsumowanie bieżącego pobierania
common-remove-entry = Usuń wpis
common-remove-entry-confirm = Czy na pewno chcesz usunąć { $entryName } z listy?
common-move-entry-top = Przenieś wpis na górę
common-move-entry-up = Przenieś wpis w górę
common-move-entry-down = Przenieś wpis w dół
common-move-entry-bottom = Przenieś wpis na dół
common-remove-completed-downloads = Usuń ukończone pobrania
common-remove-completed-downloads-confirm = Czy na pewno chcesz usunąć wszystkie ukończone pobrania z listy?
common-remove-selected-entries-confirm = Czy na pewno chcesz usunąć wybrane wpisy z listy?
common-select-all-entries = Zaznacz wszystkie wpisy
common-repair = Napraw
common-advanced-options = Opcje zaawansowane
common-extra-content = Dodatkowa zawartość
common-cache = Pamięć podręczna
common-clear-cache = Wyczyść pamięć podręczną
common-auto-clear-cache = Automatycznie czyść pamięć podręczną
common-once-a-month = Raz w miesiącu
common-once-every3-months = Raz na 3 miesiące
common-once-every6-months = Raz na 6 miesięcy
common-clear-cache-confirm = Czy na pewno chcesz wyczyścić pamięć podręczną?
common-check-log = Sprawdź pliki dziennika, aby uzyskać więcej informacji.
common-sync-game-saves-warn = Funkcja zapisywania w chmurze jest eksperymentalna. Zalecane jest utworzenie kopii zapasowej zapisów gier na wypadek, gdyby coś poszło nie tak.
common-edit-selected-download-properties = Edytuj właściwości wpisu
common-open-download-directory = Otwórz katalog pobierania
common-path-not-exists-error = Podana ścieżka nie istnieje.
common-task = Zadanie
common-download-properties = Właściwości pobierania
common-migration-completed = Migracja ukończona pomyślnie.
common-migration-no-games = Nie znaleziono gier do migracji.
common-sign-out = Wyloguj się
common-troubleshooting-information = Informacje do rozwiązywania problemów
common-playnite-version = Wersja Playnite
common-plugin-version = Wersja wtyczki
common-launcher-version = Wersja launchera
common-launcher-binary = Plik binarny launchera
common-copy-raw-data-to-clipboard = Skopiuj nieprzetworzone dane do schowka
common-log-files-path = Ścieżka plików log
common-report-bug = Zgłoś błąd
common-new-version-available = Dostępna jest nowa wersja: { $appName } { $appVersion }.
common-no-updates-available = Brak dostępnych aktualizacji.
common-view-changelog = Zobacz listę zmian
common-disable-game-update-checking = Wyłącz sprawdzanie aktualizacji
common-startup-arguments = Argumenty startowe
common-language-code = Język (kod w formacie RFC 1766)
common-launcher-settings = Modyfikuj ustawienia uruchamiania
common-alternative-exe = Alternatywny plik wykonywalny
common-cloud-saves = Zapisy w chmurze
common-check-all-dlcs = Zaznacz wszystkie dodatki (DLC)
common-check-all-content = Zaznacz wszystko
common-save-path = Ścieżka zapisu
common-cloud = Chmura
common-auto-sync-saves = Synchronizuj zapisy z chmurą
common-calculate-path = Oblicz ścieżkę
common-cloud-saves-not-supported = Ta gra nie obsługuje zapisów w chmurze.
common-manual-sync-saves = Ręczna synchronizacja zapisów
common-sync = Synchronizuj
common-download = Pobierz
common-upload = Wyślij
common-force-action = Wymuś akcję
common-cloud-save-confirm = Funkcja zapisywania w chmurze jest eksperymentalna. Zalecane jest utworzenie kopii zapasowej zapisów gry na wypadek, gdyby coś poszło nie tak. Czy na pewno chcesz kontynuować?
common-sync-playtime = Synchronizuj czas grania z chmurą
common-uploading-playtime = Przesyłanie czasu grania w grę { $gameTitle } do chmury...
common-upload-playtime-error = Wystąpił błąd podczas przesyłania czasu grania w grę { $gameTitle } do chmury.
common-move = Przenieś
common-move-confirm = Czy na pewno chcesz przenieść grę { $appName } do „{ $path }”? To może zająć sporo czasu.
common-moving-game = Przenoszenie gry { $appName } do „{ $path }”...
common-move-game-success = Gra { $appName } została pomyślnie przeniesiona do „{ $path }”.
common-move-game-error = Wystąpił błąd podczas przenoszenia gry { $appName } do „{ $path }”.
common-installed-dlcs = Zainstalowane DLC
common-available-dlcs = Dostępne DLC
common-manage-dlcs = Zarządzaj dodatkami (DLC)
common-uninstall-selected-dlcs = Czy na pewno chcesz odinstalować wybrane dodatki?
common-no-installed-dlcs = Brak zainstalowanych DLC.
common-no-available-dlcs = Brak dostępnych DLC.
common-auto-update = Automatycznie aktualizuj gry
common-games-update-policy = Sprawdzaj aktualizacje gier
common-check-updates-every-playnite-startup = Przy każdym uruchomieniu Playnite
common-remove-game-launch-settings = Usuń ustawienia uruchamiania
common-additional-services = Dodatkowe usługi
common-signed-in-as = Zalogowano jako { $userName }
common-sign-out-confirm = Czy na pewno chcesz się wylogować?
common-permission-error = Użytkownik nie ma dostępu do zapisu w określonej ścieżce. Zmień uprawnienia lub uruchom Playnite jako administrator.
common-check-for-games-updates-button = Sprawdź aktualizacje gier
common-not-enough-space = Za mało wolnego miejsca na dysku.
common-checking-for-updates = Sprawdzanie aktualizacji...
common-uninstall-success =
    { $count ->
        [one] Program { $appName } został pomyślnie odinstalowany.
       *[other] Następujące gry zostały pomyślnie odinstalowane: { $appName }.
    }
common-uninstall-error =
    { $count ->
       *[other] Nie można odinstalować następujących gier: { $appName }.
    }
common-games = Gry
common-launcher-update-policy = Sprawdzaj aktualizacje launchera
common-launcher-not-installed = Program { $launcherName } nie jest zainstalowany.
common-panel = Panel { $pluginShortName }
common-download-manager-whats-up = Pobieranie rozpocznie się już wkrótce. Możesz zobaczyć jego stan, uzyskując dostęp do panelu { $pluginShortName } za pośrednictwem Menu => Widok lub paska bocznego.
common-download-already-exists =
    { $count ->
        [one] { $appName } jest już na liście pobierania. Możesz zobaczyć jego stan, uzyskując dostęp do panelu { $pluginShortName } za pośrednictwem Menu => Widok lub paska bocznego.
       *[other] Następujące gry są już na liście pobierania: { $appName }. Możesz zobaczyć stan pobierania, uzyskując dostęp do panelu { $pluginShortName } za pośrednictwem Menu => Widok lub paska bocznego.
    }
common-migrate-games-original = Migruj wszystkie gry z wtyczki { $originalPluginShortName }
common-migrating-games-original = Migrowanie wszystkich gier z wtyczki { $originalPluginShortName }...
common-migration-confirm = Wszystkie gry zostaną usunięte z wtyczki { $originalPluginShortName } i przeniesione do { $pluginShortName }. Czy na pewno chcesz to zrobić?
common-games-updates-underway = Trwa pobieranie aktualizacji dla gier z { $updatesSourceName }.
common-instance-notice = Tylko jedna instancja { $pluginShortName } może instalować/importować/przenosić aplikacje jednocześnie. Czy chcesz wstrzymać zadania menedżera pobierania, aby kontynuować?
