common-launcher-custom-path = Caminho do inicializador
common-games-installation-path = Caminho de Instalação dos Jogos
common-download-size = Tamanho da Transferência:
common-install-size = Tamanho da Instalação:
common-uninstall-game-confirm = Tem certeza que deseja desinstalar { $gameTitle }?
common-download-settings = Transferências
common-display-download-task-finished-notifications = Notificar na área de trabalho sobre tarefas finalizadas
common-display-download-speed-in-bits = Exibir a velocidade de transferência em bits por segundo
common-download-all-dlcs = Baixar todos os DLCs
common-unattended-install = Ativar modo de instalação não assistido
common-unattended-install-tool-tip = Você não terá que escolher nada na janela do instalador e a instalação começará automaticamente após a transferência das informações necessárias.
common-max-workers = Número máximo de processos
common-max-shared-memory = Quantidade máxima de memória compartilhada (MB)
common-connection-timeout = Tempo limite da conexão (seg)
common-after-download-complete = Quando a transferência terminar
common-auto-remove-completed-downloads = Automaticamente remover transferências concluídas da lista
common-system-shutdown-countdown = O sistema será desligado em breve...
common-system-restart-countdown = O sistema será reiniciado em breve...
common-system-hibernate-countdown = O sistema hibernará em breve...
common-system-suspend-countdown = O sistema será suspenso em breve...
common-disable = Desabilitar
common-enable = Habilitar
common-space-available = Espaço Disponível:
common-after-installing = Após a instalação:
common-downloaded = Transferido
common-eta = Tempo Restante:
common-download-speed = Veloc. de Transferência:
common-disk-speed = Uso do Disco:
common-elapsed = Decorrido:
common-verifying = Verificando...
common-verifying-large-file = Verificando o arquivo grande "{ $fileName }": { $progress }
common-downloading-update = Transferindo atualização...
common-finishing-installation = Concluindo instalação...
common-finishing-update = Concluindo atualização...
common-finishing-repair = Concluindo reparo...
common-pause-download = Pausar
common-resume-download = Continuar
common-download-paused = Pausado
common-installation-finished = Instalação concluída. Divirta-se.
common-update-finished = Atualização concluída. Divirta-se.
common-repair-finished = Reparo concluído. Divirta-se.
common-sync-game-saves = Sincronizar jogos salvos na nuvem
common-syncing = Sincronizando { $gameTitle } jogo(s) salvo(s) na nuvem...
common-sync-error = Ocorreu um erro ao sincronizar { $gameTitle } jogo(s) salvo(s) na nuvem.
common-import-installed-game = Importar jogo instalado
common-importing-game = Importando { $gameTitle }...
common-import-finished = Importação concluída. Divirta-se.
common-game-import-failure = Falha ao importar o jogo. Motivo: { $reason }.
common-download-manager = Gerenciador de Transferências
common-download-status = Progresso
common-progress = Progresso
common-download-completed-column = Concluído
common-download-queued = Na fila
common-download-running = Transferindo
common-download-canceled = Cancelado
common-download-completed = Concluído
common-current-download-summary = Resumo da transferência atual
common-remove-entry = Remover da lista
common-remove-entry-confirm = Tem certeza que deseja remover { $entryName } da lista?
common-move-entry-top = Mover item para o topo
common-move-entry-up = Mover item para cima
common-move-entry-down = Mover item para baixo
common-move-entry-bottom = Mover item para o fim
common-remove-completed-downloads = Remover transferências concluídas
common-remove-completed-downloads-confirm = Tem certeza que deseja remover todas as transferências concluídos da lista?
common-remove-selected-entries-confirm = Tem certeza que deseja remover os itens selecionados da lista?
common-select-all-entries = Selecionar todos os itens
common-repair = Reparar
common-advanced-options = Opções Avançadas
common-extra-content = Conteúdo Adicional
common-cache = Cache
common-clear-cache = Apagar cache
common-auto-clear-cache = Limpar cache automaticamente
common-once-a-month = Mensalmente
common-once-every3-months = A cada 3 meses
common-once-every6-months = A cada 6 meses
common-clear-cache-confirm = Tem certeza que deseja apagar o cache?
common-check-log = Verifique os arquivos de registro para mais informações.
common-sync-game-saves-warn = A função de salvamento na nuvem é experimental. É recomendável fazer backup dos arquivos caso algo dê errado.
common-edit-selected-download-properties = Editar propriedades deste item
common-open-download-directory = Abrir diretório de transferências
common-path-not-exists-error = O caminho especificado não existe.
common-task = Tarefa
common-download-properties = Propriedades de Transferência
common-migration-completed = Migração concluída com sucesso.
common-migration-no-games = Nenhum jogo encontrado para migração.
common-sign-out = Encerrar sessão
common-troubleshooting-information = Informações para solução de problemas
common-playnite-version = Versão do Playnite
common-plugin-version = Versão do plugin
common-launcher-version = Versão do inicializador
common-launcher-binary = Executável do inicializador
common-copy-raw-data-to-clipboard = Copiar para a área de transferência
common-log-files-path = Caminho para Arquivos de Log
common-report-bug = Reportar um erro
common-new-version-available = Uma nova versão está disponível: { $appName } { $appVersion }.
common-no-updates-available = Não há atualizações disponíveis.
common-view-changelog = Ver alterações
common-disable-game-update-checking = Desativar verificação de atualização
common-startup-arguments = Argumentos de inicialização
common-language-code = Idioma (código no formato RFC 1766)
common-launcher-settings = Modificar configurações de inicialização
common-alternative-exe = Arquivo executável alternativo
common-cloud-saves = Salvamento na nuvem
common-check-all-dlcs = Marcar todos os DLCs
common-check-all-content = Marcar tudo
common-save-path = Caminho dos arquivos
common-cloud = Nuvem
common-auto-sync-saves = Sincronizar jogos salvos na nuvem
common-calculate-path = Calcular caminho
common-cloud-saves-not-supported = Este jogo não suporta salvamento na nuvem.
common-manual-sync-saves = Sincronização manual de jogos salvos
common-sync = Sincronizar
common-download = Baixar
common-upload = Enviar
common-force-action = Forçar ação
common-cloud-save-confirm = A função de salvamento na nuvem é experimental. É recomendável fazer backup dos arquivos caso algo dê errado. Tem certeza que deseja continuar?
common-sync-playtime = Sincronizar tempo de jogo com a nuvem
common-uploading-playtime = Enviando { $gameTitle } tempo(s) de jogo para a nuvem...
common-upload-playtime-error = Ocorreu um erro ao enviar { $gameTitle } tempo(s) de jogo para a nuvem.
common-move = Mover
common-move-confirm = Tem certeza que deseja mover { $appName } para "{ $path }"? Isso pode demorar.
common-moving-game = Movendo { $appName } para "{ $path }"...
common-move-game-success = { $appName } foi movido para"{ $path }" com sucesso.
common-move-game-error = Ocorreu um erro ao mover { $appName } para "{ $path }".
common-installed-dlcs = DLCs instalados
common-available-dlcs = DLCs disponíveis
common-manage-dlcs = Gerenciar DLCs
common-uninstall-selected-dlcs = Tem certeza que deseja desinstalar os DLC selecionados?
common-no-installed-dlcs = Nenhum DLC instalado.
common-no-available-dlcs = Nenhum DLC disponível.
common-auto-update = Atualizar jogos automaticamente
common-games-update-policy = Verificar atualizações de jogos
common-check-updates-every-playnite-startup = Em toda inicialização do Playnite
common-remove-game-launch-settings = Remover configurações de inicialização
common-additional-services = Serviços adicionais
common-signed-in-as = Conectado como { $userName }
common-sign-out-confirm = Tem certeza de que deseja sair?
common-permission-error = Usuário não tem permissão de escrita no caminho especificado. Altere as permissões ou inicie o Playnite como administrador.
common-check-for-games-updates-button = Verificar atualizações de jogos
common-not-enough-space = Espaço em disco insuficiente.
common-checking-for-updates = Procurando atualizações...
common-uninstall-success =
    { $count ->
        [one] { $appName } foi desinstalado com sucesso.
       *[other] Os seguintes jogos foram desinstalados com êxito: { $appName }.
    }
common-uninstall-error =
    { $count ->
       *[other] Não é possível desinstalar seguintes jogos: { $appName }.
    }
common-games = Jogos
common-launcher-update-policy = Procurar por atualizações do inicializador
common-launcher-not-installed = { $launcherName } não está instalado.
common-panel = Painel { $pluginShortName }
common-download-manager-whats-up = A transferência começará em breve. Você pode conferir o progresso pelo Painel { $pluginShortName } através do Menu ⇒ Visualização ou pela Barra Lateral.
common-download-already-exists =
    { $count ->
        [one] { $appName } já está na lista de transferências. Você pode conferir o progresso pelo Painel { $pluginShortName } através do Menu ⇒ Visualização ou pela Barra Lateral.
       *[other] Os seguintes jogos já estão na lista de transferências: { $appName }. Você pode ver o progresso da transferência acessando o Painel { $pluginShortName } através do Menu ⇒ Visualização ou pela barra lateral.
    }
common-migrate-games-original = Migrar todos os jogos do plugin { $originalPluginShortName }
common-migrating-games-original = Migrando todos os jogos do plugin { $originalPluginShortName }...
common-migration-confirm = Todos os jogos serão removidos do plugin { $originalPluginShortName } e movidos para o { $pluginShortName }. Tem certeza disso?
common-games-updates-underway = Atualizações de jogos da { $updatesSourceName } estão sendo transferidas.
common-instance-notice = Apenas uma instância do { $pluginShortName } pode instalar/importar/mover aplicativos por vez. Você deseja pausar as tarefas do gerenciador de transferências para continuar?
