common-games-installation-path = Žaidimų įdiegimo kelias
common-download-size = Atsisiuntimo dydis:
common-install-size = Įdiegties dydis:
common-uninstall-game-confirm = Ar tikrai norite išdiegti { $gameTitle }?
common-max-shared-memory = Maksimalus bendros atminties kiekis (MB)
common-space-available = Yra vietos:
common-eta = Numatomas baigties laikas:
common-download-speed = Siuntimosi greitis:
common-elapsed = Praėjo:
common-pause-download = Pristabdyti
common-resume-download = Pratęsti
common-download-paused = Pristabdyta
common-installation-finished = Diegimas baigtas. Smagaus.
common-importing-game = Importuojama { $gameTitle }...
common-import-finished = Importas baigtas. Smagaus.
common-download-manager = Atsisiuntimų Tvarkyklė
common-download-status = Būsena
common-download-completed-column = Baigta
common-download-queued = Laukia eilėje
common-download-running = Vykdoma
common-download-canceled = Atšaukta
common-download-completed = Baigta
common-current-download-summary = Dabartinio siuntimosi santrauka
common-remove-entry = Pašalinti įrašą
common-remove-entry-confirm = Ar tikrai norite pašalinti { $entryName } iš sąrašo?
common-repair = Sutaisyti
common-advanced-options = Išplėstinės Parinktys
common-cache = Podėlis
common-clear-cache = Išvalyti podėlį
common-auto-clear-cache = Podėlį išvalyti automatškai
common-once-a-month = Kartą per mėnesį
common-once-every3-months = Kartą per 3 mėnesius
common-once-every6-months = Kartą per 6 mėnesius
common-clear-cache-confirm = Ar tikrai norite išvalyti podėlį?
common-check-log = Daugiau informacijos ieškokite žurnaluose.
