common-launcher-custom-path = Başlatıcı Yolu
common-games-installation-path = Oyunların Kurulum Yolu
common-download-size = İndirme Boyutu:
common-install-size = Kurulum Boyutu:
common-uninstall-game-confirm = { $gameTitle } kaldırılacak, bundan emin misiniz?
common-download-settings = İndirilenler
common-display-download-task-finished-notifications = Tamamlanan görevlerle ilgili masaüstü bildirimlerini görüntüle
common-display-download-speed-in-bits = İndirme hızını saniyedeki bit cinsinden göster
common-download-all-dlcs = Tüm DLC içeriğini indir
common-unattended-install = Katılımsız kurulum modunu etkinleştir
common-unattended-install-tool-tip = Kurulum penceresinde herhangi bir şey seçmeniz gerekiyor ve gerekli bilgiler indirildikten sonra kurulum otomatik olarak başlayacaktır.
common-max-workers = En fazla çalışan işlem sayısı
common-max-shared-memory = En fazla paylaşılan bellek miktarı (MB)
common-connection-timeout = Bağlantı zaman aşımı (sn)
common-after-download-complete = İndirme tamamlandıktan sonraki eylem
common-auto-remove-completed-downloads = Tamamlanan indirmeleri otomatik olarak listeden kaldır
common-system-shutdown-countdown = Sistem yakında kapatılacak...
common-system-restart-countdown = Sistem yakında yeniden başlatılacak...
common-system-hibernate-countdown = Sistem yakında hazırda bekletme moduna geçecek...
common-system-suspend-countdown = Sistem yakında askıya alınacak...
common-disable = Etkisizleştir
common-enable = Etkinleştir
common-space-available = Mevcut Alan:
common-after-installing = Kurulumdan Sonra:
common-downloaded = İndirilen
common-eta = TTS:
common-download-speed = İndirme Hızı:
common-disk-speed = Disk Kullanımı:
common-elapsed = Geçen:
common-verifying = Verifying...
common-verifying-large-file = Büyük dosya doğrulanıyor "{ $fileName }": { $progress }
common-downloading-update = Güncelleştirme indiriliyor...
common-finishing-installation = Kurulum tamamlanıyor...
common-finishing-update = Güncelleme tamamlanıyor...
common-finishing-repair = Onarım tamamlanıyor...
common-pause-download = Duraklat
common-resume-download = Sürdür
common-download-paused = Duraklatıldı
common-installation-finished = Kurulum tamamlandı. İyi eğlenceler.
common-update-finished = Güncelleme tamamlandı. İyi eğlenceler.
common-repair-finished = Onarım tamamlandı. İyi eğlenceler.
common-sync-game-saves = Oyun kayıtlarını buluta eşitle
common-syncing = { $gameTitle } oyun kaydı buluta eşitleniyor...
common-sync-error = { $gameTitle } oyun kaydı buluta eşitlenirken bir hata oluştu.
common-import-installed-game = Kurulu oyunu içe aktar
common-importing-game = İçe aktarılıyor { $gameTitle }...
common-import-finished = İçe aktarma tamamlandı. İyi eğlenceler.
common-game-import-failure = Oyun içe aktarılamadı. Sebep: { $reason }.
common-download-manager = İndirme Yöneticisi
common-download-status = Durum
common-progress = İlerleyiş
common-download-completed-column = Tamamlandı
common-download-queued = Kuyrukta
common-download-running = Çalışıyor
common-download-canceled = Vazgeçildi
common-download-completed = Tamamlandı
common-current-download-summary = Mevcut indirmenin özeti
common-remove-entry = Girdiyi kaldır
common-remove-entry-confirm = { $entryName } öğesini listeden çıkarmak istediğinizden emin misiniz?
common-move-entry-top = Girişi en üste taşı
common-move-entry-up = Girişi üste taşı
common-move-entry-down = Girişi alta taşı
common-move-entry-bottom = Girişi en alta taşı
common-remove-completed-downloads = Tamamlanan indirmeleri kaldır
common-remove-completed-downloads-confirm = Tamamlanan tüm indirmeleri listeden kaldırmak istiyor musunuz?
common-remove-selected-entries-confirm = Seçilen girişleri listeden kaldırmak istiyor musunuz?
common-select-all-entries = Tüm girişleri seç
common-repair = Onar
common-advanced-options = Gelişmiş Seçenekler
common-extra-content = Ekstra İçerik
common-cache = Önbellek
common-clear-cache = Önbelleği temizle
common-auto-clear-cache = Önbelleği otomatik temizle
common-once-a-month = Ayda bir kez
common-once-every3-months = 3 ayda bir kez
common-once-every6-months = 6 ayda bir kez
common-clear-cache-confirm = Önbelleği temizlemek istediğinizden emin misiniz?
common-check-log = Daha fazla bilgi için günlük dosyalarını kontrol edin.
common-sync-game-saves-warn = Bulut kaydetme özelliği deneyseldir. Bir şeyler ters giderse diye oyun kayıtlarını yedeklemeniz önerilir.
common-edit-selected-download-properties = Girdi özelliklerini düzenle
common-open-download-directory = İndirilenler dizinini aç
common-path-not-exists-error = Belirtilen yol mevcut değil.
common-task = Görev
common-download-properties = İndirme Özellikleri
common-migration-completed = Taşıma başarıyla tamamlandı.
common-migration-no-games = Taşıma için oyun bulunamadı.
common-sign-out = Oturumu kapat
common-troubleshooting-information = Sorun giderme bilgisi
common-playnite-version = Playnite sürümü
common-plugin-version = Eklenti sürümü
common-launcher-version = Başlatıcı sürümü
common-launcher-binary = Başlatıcı binary
common-copy-raw-data-to-clipboard = Ham verileri panoya kopyala
common-log-files-path = Günlük Dosyaları Yolu
common-report-bug = Bir hata bildir
common-new-version-available = Yeni bir sürüm mevcut: { $appName } { $appVersion }.
common-no-updates-available = Güncelleme yok.
common-view-changelog = Değişiklikleri görüntüle
common-disable-game-update-checking = Güncelleme kontrolünü kapat
common-startup-arguments = Başlangıç ​​etkenleri
common-language-code = Dil (RFC 1766 biçiminde kod)
common-launcher-settings = Başlatma ayarlarını değiştir
common-alternative-exe = Alternatif yürütülebilir dosya
common-cloud-saves = Bulut kayıtları
common-check-all-dlcs = Tüm DLC içerikleri denetle
common-check-all-content = Tümünü denetle
common-save-path = Kayıt yolu
common-cloud = Bulut
common-auto-sync-saves = Kayıtları buluta eşitle
common-calculate-path = Yolu hesapla
common-cloud-saves-not-supported = Bu oyun buluta kaydetmeyi desteklemiyor.
common-manual-sync-saves = El ile eşitlenen kayıtlar
common-sync = Eşitleme
common-download = İndir
common-upload = Yükle
common-force-action = Eylemi zorla
common-cloud-save-confirm = Bulut kaydetme özelliği deneyseldir. Bir şeylerin ters gitmesi durumunda oyun kayıtlarının yedeklenmesi önerilir. Devam etmek istediğine emin misin?
common-sync-playtime = Oynatma süresini bulutla eşitle
common-uploading-playtime = { $gameTitle } oyun oynama süresi buluta yükleniyor...
common-upload-playtime-error = { $gameTitle } oyun oynama süresi buluta yüklenirken bir hata oluştu.
common-move = Taşı
common-move-confirm = { $appName } öğesini "{ $path }" konumuna taşımak istediğinizden emin misiniz? Bu uzun zaman alabilir.
common-moving-game = { $appName }, "{ $path }" öğesine taşınıyor...
common-move-game-success = { $appName } başarıyla "{ $path }" konumuna taşındı.
common-move-game-error = { $appName }, "{ $path }" konumuna taşınırken bir hata oluştu.
common-installed-dlcs = Kurulu DLC
common-available-dlcs = Mevcut DLC
common-manage-dlcs = DLC Yönetimi
common-uninstall-selected-dlcs = Seçili DLC içerikleri kaldırmak istediğinizden emin misiniz?
common-no-installed-dlcs = Kurulu DLC yok.
common-no-available-dlcs = Mevcut DLC yok.
common-auto-update = Oyunları otomatik olarak güncelle
common-games-update-policy = Oyun güncellemelerini denetle
common-check-updates-every-playnite-startup = Playnite her başlangıcında
common-remove-game-launch-settings = Başlatma ayarlarını kaldır
common-additional-services = Ek servisler
common-signed-in-as = { $userName } olarak oturum açıldı
common-sign-out-confirm = Oturumu kapatmak istiyor musunuz?
common-permission-error = Kullanıcının belirtilen yola yazma erişimi yok. İzinleri değiştirin veya Playnite programını yönetici olarak başlatın.
common-check-for-games-updates-button = Oyun güncellemelerini denetle
common-not-enough-space = Yeterli boş disk alanı yok.
common-checking-for-updates = Güncellemeler kontrol ediliyor...
common-uninstall-success =
    { $count ->
        [one] { $appName } başarıyla kaldırıldı.
       *[other] Aşağıdaki oyunlar başarıyla kaldırıldı: { $appName }.
    }
common-uninstall-error =
    { $count ->
       *[other] Aşağıdaki oyunlar kaldırılamıyor: { $appName }.
    }
common-games = Oyunlar
common-launcher-update-policy = Başlatıcı güncellemelerini denetle
common-launcher-not-installed = { $launcherName } kurulu değil.
common-panel = { $pluginShortName } Paneli
common-download-manager-whats-up = İndirme yakında başlayacak. Menü => Görünüm veya kenar çubuğundan { $pluginShortName } Panel üstünden durumunu görebilirsiniz.
common-download-already-exists =
    { $count ->
        [one] { $appName } zaten indirme listesinde. Menü => Görünüm veya kenar çubuğundan { $pluginShortName } Panel üstünden indirmenin durumunu görebilirsiniz.
       *[other] Şu oyunlar zaten indirme listesinde bulunuyor: { $appName }. Menü => Görünüm veya kenar çubuğundan { $pluginShortName } Panele erişerek indirme durumunu görebilirsiniz.
    }
common-migrate-games-original = Tüm oyunları { $originalPluginShortName } eklentisinden taşıyın
common-migrating-games-original = Tüm oyunları { $originalPluginShortName } eklentisinden taşıyınıyor...
common-migration-confirm = Tüm oyunlar { $originalPluginShortName } eklentisinden kaldırılacak ve { $pluginShortName } üstüne taşınacak. Bunu yapmak istediğinden emin misin?
common-games-updates-underway = { $updatesSourceName } oyunlarına yönelik güncellemeler indiriliyor.
common-instance-notice = Aynı anda yalnızca bir { $pluginShortName } örneği uygulamaları kurulabilir/içe aktarabilir/taşıyabilir. Devam etmek için indirme yöneticisi görevlerini duraklatmak istiyor musunuz?
