common-launcher-custom-path = Launcher Pfad
common-games-installation-path = Spiele-Installationspfad
common-download-size = Downloadgröße:
common-install-size = Installationsgröße:
common-uninstall-game-confirm = Sind Sie sicher, dass Sie { $gameTitle } deinstallieren möchten?
common-display-download-task-finished-notifications = Desktop-Benachrichtigungen über abgeschlossene Aufgaben anzeigen
common-display-download-speed-in-bits = Downloadgeschwindigkeit in Bits pro Sekunde anzeigen
common-download-all-dlcs = Alle DLCs herunterladen
common-unattended-install = Aktiviere unbeaufsichtigten Installationsmodus
common-unattended-install-tool-tip = Sie müssen im Installationsfenster nichts auswählen und die Installation wird automatisch nach dem Herunterladen der benötigten Informationen gestartet.
common-max-workers = Maximale Anzahl von Arbeits-Prozessen
common-max-shared-memory = Maximale Anzahl an geteiltem Speicher (MB)
common-connection-timeout = Verbindungsunterbrechung (Sek)
common-disable = Deaktivieren
common-enable = Aktivieren
common-space-available = Verfügbarer Speicherplatz:
common-after-installing = Nach der Installation:
common-downloaded = Heruntergeladen
common-eta = Downloadzeit:
common-download-speed = Downloadgeschwindigkeit:
common-disk-speed = Festplattennutzung:
common-elapsed = Vergangene Zeit:
common-verifying = Überprüfe...
common-verifying-large-file = Überprüfe große Datei "{ $fileName }": { $progress }
common-downloading-update = Aktualisierung wird heruntergeladen…
common-finishing-installation = Installation wird abgeschlossen...
common-finishing-update = Update wird abgeschlossen...
common-finishing-repair = Reparatur wird abgeschlossen...
common-pause-download = Anhalten
common-resume-download = Fortsetzen
common-download-paused = Pausiert
common-installation-finished = Installation abgeschlossen. Viel Spaß.
common-update-finished = Update abgeschlossen. Viel Spaß.
common-repair-finished = Reparatur abgeschlossen. Viel Spaß.
common-sync-game-saves = Spielstände mit der Cloud synchronisieren
common-syncing = Synchronisiere { $gameTitle } Spielstände mit der Cloud...
common-sync-error = Beim Synchronisieren von { $gameTitle } Spielständen mit der Cloud ist ein Fehler aufgetreten.
common-import-installed-game = Installiertes Spiel importieren
common-importing-game = Importiere { $gameTitle }...
common-import-finished = Import abgeschlossen. Viel Spaß.
common-game-import-failure = Spiel konnte nicht importiert werden. Grund: { $reason }.
common-download-manager = Download-Manager
common-download-status = Status
common-progress = Fortschritt
common-download-completed-column = Abgeschlossen
common-download-queued = Ausstehend
common-download-running = Aktiv
common-download-canceled = Abgebrochen
common-download-completed = Abgeschlossen
common-current-download-summary = Zusammenfassung des aktuellen Downloads
common-remove-entry = Eintrag entfernen
common-remove-entry-confirm = Sind Sie sicher, dass Sie { $entryName } aus der Liste entfernen möchten?
common-move-entry-top = Eintrag an den Anfang verschieben
common-move-entry-up = Eintrag nach oben verschieben
common-move-entry-down = Eintrag nach unten verschieben
common-move-entry-bottom = Eintrag ans Ende verschieben
common-remove-completed-downloads = Abgeschlossene Downloads entfernen
common-remove-completed-downloads-confirm = Sind Sie sicher, dass Sie alle abgeschlossenen Downloads aus der Liste entfernen möchten?
common-remove-selected-entries-confirm = Sind Sie sicher, dass Sie die ausgewählten Einträge aus der Liste entfernen möchten?
common-select-all-entries = Alle Einträge auswählen
common-repair = Reparieren
common-advanced-options = Erweiterte Einstellungen
common-extra-content = Extra Content
common-cache = Zwischenspeicher
common-clear-cache = Zwischenspeicher leeren
common-auto-clear-cache = Zwischenspeicher automatisch leeren
common-once-a-month = Einmal pro Monat
common-once-every3-months = Einmal alle 3 Monate
common-once-every6-months = Einmal alle 6 Monate
common-clear-cache-confirm = Sind Sie sicher, dass Sie den Zwischenspeicher leeren möchten?
common-check-log = Überprüfen Sie die Logdateien für weitere Informationen.
common-sync-game-saves-warn = Die Cloud-Speicherstands-Funktion ist experimentell. Es wird empfohlen, Spielstände zu sichern, falls etwas schief geht.
common-edit-selected-download-properties = Eintragseigenschaften bearbeiten
common-open-download-directory = Download-Verzeichnis öffnen
common-path-not-exists-error = Der angegebene Pfad existiert nicht.
common-task = Aufgabe
common-download-properties = Download-Eigenschaften
common-migration-completed = Migration erfolgreich abgeschlossen.
common-migration-no-games = Keine Spiele für die Migration gefunden.
common-sign-out = Abmelden
common-troubleshooting-information = Informationen zur Fehlerbehebung
common-playnite-version = Playnite Version
common-plugin-version = Plugin-Version
common-launcher-version = Launcher Version
common-launcher-binary = Launcher-Binärdatei
common-copy-raw-data-to-clipboard = Rohdaten in die Zwischenablage kopieren
common-log-files-path = Log-Dateipfad
common-report-bug = Einen Fehler melden
common-new-version-available = Eine neue Version ist verfügbar: { $appName } { $appVersion }.
common-no-updates-available = Keine Aktualisierungen verfügbar
common-view-changelog = Änderungsprotokoll anzeigen
common-disable-game-update-checking = Updateprüfung deaktivieren
common-startup-arguments = Startparameter
common-language-code = Sprache (Code im RFC 1766 Format)
common-launcher-settings = Starteinstellungen ändern
common-alternative-exe = Alternative ausführbare Datei
common-cloud-saves = Cloud Spielstände
common-check-all-dlcs = Überprüfe alle DLCs
common-check-all-content = Alle auswählen
common-save-path = Speicherstände Dateipfad
common-cloud = Cloud
common-auto-sync-saves = Speicherstände mit der Cloud Synchronisieren
common-calculate-path = Pfad berechnen
common-cloud-saves-not-supported = Dieses Spiel unterstützt keine Cloud-Speicherstände.
common-manual-sync-saves = Manuelle Synchronisierung der Speicherstände
common-sync = Synchronisieren
common-download = Herunterladen
common-upload = Hochladen
common-cloud-save-confirm = Die Cloud-Speicherstände-Funktion ist experimentell. Es wird empfohlen, Spielstände zu sichern, falls etwas schief geht. Sind Sie sicher, dass Sie fortfahren möchten?
common-sync-playtime = Synchronisiere Spielzeit mit der Cloud
common-uploading-playtime = Lade { $gameTitle } Spielzeit in die Cloud hoch...
common-upload-playtime-error = Beim Hochladen von { $gameTitle } Spielzeit in die Cloud ist ein Fehler aufgetreten.
common-move = Verschieben
common-move-confirm = Sind Sie sicher, dass Sie { $appName } nach "{ $path }" verschieben möchten? Dies kann eine lange Zeit dauern.
common-moving-game = Verschiebe { $appName } nach "{ $path }"...
common-move-game-success = { $appName } wurde erfolgreich nach "{ $path } " verschoben.
common-move-game-error = Beim Verschieben von { $appName } nach "{ $path } " ist ein Fehler aufgetreten.
common-installed-dlcs = Installierte DLCs
common-available-dlcs = Verfügbare DLCs
common-manage-dlcs = DLCs verwalten
common-uninstall-selected-dlcs = Sind Sie sicher, dass Sie die ausgewählten DLCs deinstallieren möchten?
common-no-installed-dlcs = Keine installierten DLCs.
common-no-available-dlcs = Keine verfügbaren DLCs.
common-auto-update = Spiele automatisch aktualisieren
common-games-update-policy = Nach Spiel-Aktualisierungen suchen
common-check-updates-every-playnite-startup = Bei jedem Start von Playnite
common-remove-game-launch-settings = Starteinstellungen entfernen
common-additional-services = Zusätzliche Dienste
common-signed-in-as = Angemeldet als { $userName }
common-sign-out-confirm = Sind Sie sicher, dass Sie sich abmelden möchten?
common-permission-error = Benutzer hat keinen Schreibzugriff auf den angegebenen Pfad. Ändern Sie die Berechtigungen oder starten Sie Playnite als Administrator.
common-check-for-games-updates-button = Nach Spiel-Aktualisierungen suchen
common-not-enough-space = Nicht genügend freier Speicherplatz.
common-checking-for-updates = Suche nach Aktualisierungen...
common-uninstall-success =
    { $count ->
        [one] { $appName } wurde erfolgreich deinstalliert.
       *[other] Folgende Spiele wurden erfolgreich deinstalliert: { $appName }.
    }
common-uninstall-error =
    { $count ->
       *[other] Folgende Spiele können nicht deinstalliert werden: { $appName }.
    }
common-games = Spiele
