common-sync-game-saves = Spielstände mit der Cloud synchronisieren
common-syncing = Synchronisiere { $gameTitle } Spielstände mit der Cloud...
common-sync-game-saves-warn = Die Cloud-Speicherstands-Funktion ist experimentell. Es wird empfohlen, Spielstände zu sichern, falls etwas schief geht.
common-cloud-saves = Cloud Spielstände
common-save-path = Speicherstände Dateipfad
common-cloud = Cloud
common-auto-sync-saves = Speicherstände mit der Cloud Synchronisieren
common-calculate-path = Pfad berechnen
common-cloud-saves-not-supported = Dieses Spiel unterstützt keine Cloud-Speicherstände.
common-sync = Synchronisieren
common-download = Herunterladen
common-upload = Hochladen
common-cloud-save-confirm = Die Cloud-Speicherstände-Funktion ist experimentell. Es wird empfohlen, Spielstände zu sichern, falls etwas schief geht. Sind Sie sicher, dass Sie fortfahren möchten?
common-sync-playtime = Synchronisiere Spielzeit mit der Cloud
common-uploading-playtime = Lade { $gameTitle } Spielzeit in die Cloud hoch...
common-upload-playtime-error = Beim Hochladen von { $gameTitle } Spielzeit in die Cloud ist ein Fehler aufgetreten.
common-manual-sync-saves = Manuelle Synchronisierung der Speicherstände
