common-games-installation-path = Ruta de instalación de juegos
common-download-size = Tamaño de descarga:
common-install-size = Tamaño de instalación:
common-uninstall-game-confirm = ¿Estás seguro que deseas desinstalar { $gameTitle }?
common-download-settings = Descargas
common-display-download-task-finished-notifications = Mostrar notificaciones de escritorio sobre tareas terminadas
common-display-download-speed-in-bits = Mostrar velocidad de descarga en bits por segundo
common-unattended-install = Activar el modo de instalación desatendida
common-unattended-install-tool-tip = Perfecto, aquí tienes la traducción ajustada:
common-max-workers = Número máximo de procesos de trabajo
common-max-shared-memory = Cantidad máxima de memoria compartida (MB)
common-connection-timeout = Tiempo de espera de conexión (segundos)
common-after-download-complete = Acción después de completar la descarga
common-auto-remove-completed-downloads = Eliminar automáticamente las descargas completadas de la lista
common-system-shutdown-countdown = El sistema se apagará pronto...
common-system-restart-countdown = El sistema se reiniciará pronto...
common-system-hibernate-countdown = El sistema entrará en hibernación pronto...
common-system-suspend-countdown = El sistema se suspenderá pronto...
common-space-available = Espacio disponible:
common-after-installing = Después de instalar:
common-downloaded = Descargado
common-eta = Estimado:
common-download-speed = Velocidad de descarga:
common-disk-speed = Uso del disco:
common-elapsed = Transcurrido:
common-verifying = Verificando...
common-verifying-large-file = Verificando archivo grande "{ $fileName }": { $progress }
common-downloading-update = Descargando actualización...
common-finishing-installation = Finalizando instalación...
common-finishing-update = Finalizando actualización...
common-finishing-repair = Finalizando reparación...
common-pause-download = Pausar
common-resume-download = Reanudar
common-download-paused = Pausado
common-installation-finished = Instalación terminada. Diviértete.
common-update-finished = Actualización terminada. Diviértete.
common-repair-finished = Reparación terminada. Diviértete.
common-sync-error = Se ha producido un error al sincronizar { $gameTitle } juegos guardados en la nube.
common-import-installed-game = Importar juego instalado
common-importing-game = Importando { $gameTitle }...
common-import-finished = Importación terminada. Diviértete.
common-download-manager = Gestor de descargas
common-download-status = Estado
common-progress = Progreso
common-download-completed-column = Completado
common-download-queued = En cola
common-download-running = En ejecución
common-download-canceled = Cancelado
common-download-completed = Completado
common-remove-entry = Remover de la lista
common-remove-entry-confirm = ¿Está seguro que desea eliminar { $entryName } de la lista?
common-move-entry-top = Mover entrada a la parte superior
common-move-entry-up = Mover entrada arriba
common-move-entry-down = Mover entrada abajo
common-move-entry-bottom = Mover la entrada a la parte inferior
common-remove-completed-downloads = Eliminar descargas completadas
common-remove-completed-downloads-confirm = ¿Estás seguro que deseas eliminar todas las descargas completadas de la lista?
common-remove-selected-entries-confirm = ¿Estás seguro que deseas eliminar las entradas seleccionadas de la lista?
common-select-all-entries = Seleccionar todas las entradas
common-repair = Reparar
common-advanced-options = Opciones Avanzadas
common-cache = Caché
common-clear-cache = Borrar caché
common-auto-clear-cache = Borrar caché automáticamente
common-once-a-month = Una vez al mes
common-once-every3-months = Una vez cada 3 meses
common-once-every6-months = Una vez cada 6 meses
common-clear-cache-confirm = ¿Estás seguro de que quieres borrar el caché?
common-check-log = Revisa los archivos de registro para más información.
common-edit-selected-download-properties = Editar propiedades de la entrada
common-open-download-directory = Abrir directorio de descarga
common-path-not-exists-error = La ruta especificada no existe.
common-task = Tarea
common-download-properties = Propiedades de la descarga
common-migration-completed = Migración completada con éxito.
common-migration-no-games = No se encontraron juegos para la migración.
common-sign-out = Cerrar sesión
common-troubleshooting-information = Información para solucionar problemas
common-playnite-version = Versión de Playnite
common-plugin-version = Versión del plugin
common-copy-raw-data-to-clipboard = Copiar datos sin procesar al portapapeles
common-log-files-path = Ruta de archivos de registro
common-report-bug = Reportar un error
common-new-version-available = Una nueva versión está disponible: { $appName } { $appVersion }.
common-no-updates-available = No hay actualizaciones disponibles.
common-view-changelog = Ver lista de cambios
common-disable-game-update-checking = Desactivar comprobación de actualización
common-startup-arguments = Argumentos de inicio
common-launcher-settings = Modificar ajustes de inicio
common-alternative-exe = Archivo ejecutable alternativo
common-check-all-content = Marcar todo
common-move = Mover
common-move-confirm = ¿Estás seguro de que quieres mover { $appName } a "{ $path }"? Esto puede tardar mucho tiempo.
common-moving-game = Moviendo { $appName } a "{ $path }"...
common-move-game-success = { $appName } se ha movido con éxito a "{ $path }".
common-move-game-error = Se ha producido un error al mover { $appName } a "{ $path }".
common-auto-update = Actualizar automáticamente los juegos
common-games-update-policy = Buscar actualizaciones de juegos
common-check-updates-every-playnite-startup = En cada inicio de Playnite
common-remove-game-launch-settings = Eliminar la configuración de lanzamiento
common-signed-in-as = Sesión iniciada como { $userName }
common-sign-out-confirm = ¿Estás seguro de que quieres cerrar sesión?
common-permission-error = El usuario no tiene acceso de escritura a la ruta especificada. Cambie los permisos o ejecute Playnite como administrador.
common-check-for-games-updates-button = Buscar actualizaciones de juegos
common-not-enough-space = No hay suficiente espacio libre en disco.
common-checking-for-updates = Buscando actualizaciones...
common-uninstall-success =
    { $count ->
        [one] { $appName } se ha desinstalado correctamente.
       *[other] Los siguientes juegos se han desinstalado correctamente: { $appName }.
    }
common-uninstall-error =
    { $count ->
       *[other] No se puede desinstalar los siguientes juegos: { $appName }.
    }
common-games = Juegos
common-launcher-not-installed = { $launcherName } no está instalado.
common-panel = Panel { $pluginShortName }
common-download-manager-whats-up = La descarga comenzará pronto. Puedes ver su estado accediendo al Panel { $pluginShortName } a través del Menú => Vista o barra lateral.
common-download-already-exists =
    { $count ->
        [one] { $appName } ya está en la lista de descarga. Puede ver el estado de la descarga accediendo al Panel { $pluginShortName } a través del Menú => Vista o barra lateral.
       *[other] Los siguientes juegos ya están en la lista de descargas: { $appName }. Puede ver el estado de la descarga accediendo al Panel { $pluginShortName } a través del Menú => Vista o barra lateral.
    }
common-migrate-games-original = Migrar todos los juegos del complemento { $originalPluginShortName }
common-migrating-games-original = Migrando todos los juegos desde el complemento { $originalPluginShortName }...
common-migration-confirm = Todos los juegos serán eliminados del complemento { $originalPluginShortName } y movidos a { $pluginShortName }. ¿Estás seguro de que quieres hacer esto?
common-games-updates-underway = Se están descargando actualizaciones para los juegos de { $updatesSourceName }.
common-instance-notice = Sólo una instancia de { $pluginShortName } puede instalar/importar/mover aplicaciones a la vez. ¿Quieres pausar las tareas del administrador de descargas para continuar?
