id = "hawkeye116477.LegendaryLibrary"
name = "Legendary (Epic Games) library integration"
author = "hawkeye116477"
version = "_version_"
module = "LegendaryLibrary.dll"
icon = "Resources\\legendary_icon.ico"
client_app_icon = "Resources\\legendary_icon.ico"
library_icon = "Resources\\legendary_icon.ico"
source_link = "https://github.com/hawkeye116477/playnite-legendary-plugin/tree/P11"
help_link = "https://github.com/hawkeye116477/playnite-legendary-plugin/wiki"

[[dependencies]]
addon_id = "hawkeye116477.UDM"
min_version = "2.0"
is_optional = true
